# Generated by Django 4.1.7 on 2023-06-10 20:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_illness_delete_prescriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='prescriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescriptions', models.TextField(blank=True)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('doctor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.staff')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.patient')),
            ],
        ),
        migrations.CreateModel(
            name='illness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('illness', models.TextField(blank=True)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('doctor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.staff')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.patient')),
            ],
        ),
    ]
